//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace file_manager_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string type { get; set; }
        public string mark { get; set; }
        public bool isshared { get; set; }
        public System.DateTime createtime { get; set; }
        public int User_id { get; set; }
        public int Folder_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Folder Folder { get; set; }
    }
}
